### PR TITLE
Retrieve Map Service outputs

### PR DESCRIPTION
**Pull request by rowanwins**
Hi @jgravois 

As discussed attached is a first crack at retrieving map services from a geoprocessing task. Let me know what you think.

Cheers
Rowan

### CODE REVIEW

**Comment by jgravois** [comment]
thanks for this @rowanwins.

i'd recommend tweaking `processGPOutput()` a bit in the interest of legibility:

```js
processGPOutput: function(response) {
  var processedResponse = {};
  var responseValue;

  // grab syncronous results
  if (this.options.async === false) {
    responseValue = response.results[0].value;
  }

  //grab async results slightly differently
  else {
    processedResponse.jobId = this._currentJobId;
    responseValue = response.value;
  }

  // if output is a raster layer, we also need to stub out a MapService url using jobid
  if (this.options.async === true && response.dataType === 'GPRasterDataLayer') {
    var baseURL = this.options.url;
    var n = baseURL.indexOf('GPServer');
    var serviceURL = baseURL.slice(0,n)+'MapServer/';
    processedResponse.outputMapService = serviceURL+'jobs/'+this._currentJobId;
  }

  // if output is GPFeatureRecordSetLayer, convert to GeoJSON
  if (responseValue.features) {
    var featureCollection = L.esri.Util.responseToFeatureCollection(responseValue);
    processedResponse.features = featureCollection.features;
  }

  // if the output is a file, pass it along 'as is'
  if (response.dataType === 'GPDataFile') {
    processedResponse.outputFile = response.results[0];
  }

  // to do:
  // confirm we can pass back output booleans, strings and numbers too.

  return processedResponse;
}
```

happy to merge your pull request if you agree this is an improvement.  also, i think the `debug` folder is a better place for `mapService-example.html` than the root of the repo.

after everything is tidied up, would you be game for a [squash](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)?

**Comment by jgravois** [comment]
oh yeah, can you update the [GPResults](https://github.com/jgravois/esri-leaflet-gp#gp-results) README doc too?

**Comment by rowanwins** [comment]
Thanks @jgravois , have tweaked things as per your suggestions, am about to attempt to squash the commits, hopefully things do not blow up :)
Cheers
Rowan

**Comment by rowanwins** [comment]
Well the rebase was a dismal failure I think @jgravois , sorry about that, next time I'll try and keep it a bit cleaner

**Comment by jgravois** [comment]
no worries at all @rowanwins.  thanks for taking the time to help with this.  you're a :star2: :

**Comment by rowanwins** [comment]
No worries @jgravois , glad to make a small contribution!

**Pull request merged**
